name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/*
      - include/*
      - meson.build
      - .github/workflows/ci.yml

  pull_request:
    paths:
      - src/*
      - include/*
      - meson.build
      - .github/workflows/ci.yml

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update package lists
        run: sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get install -y meson ninja-build \
            libnm-dev libglib2.0-dev network-manager-dev \
            clang-tools build-essential
      - name: Setup Meson build environment
        run: meson setup build
      - name: Compile project
        run: ninja -C build
      - name: Run tests
        run: ninja -C build test
      - name: Run static analysis
        run: ninja -C build scan-build
